import type {
  GameEvent,
  GameMap,
  GameState,
  PlayerCommand,
  PlayerId,
  RejectionReason,
  ScenarioType,
  SpecialtyType,
} from "@zombie/game-core";

/** Bumped on any incompatible change. The server sends it in `joined`; clients compare. */
export const PROTOCOL_VERSION = 3;

/** Lobby limits shared by both sides so the client can validate before sending. */
export const PLAYER_NAME_MIN_LENGTH = 1;
export const PLAYER_NAME_MAX_LENGTH = 20;
export const MAX_PLAYERS = 4;

/**
 * A player command as the client sends it: without `playerId`, which the server stamps
 * from the session. Distributes over the union so each member loses only that field.
 */
export type ClientCommand = PlayerCommand extends infer C
  ? C extends PlayerCommand
    ? Omit<C, "playerId">
    : never
  : never;

// ---------------------------------------------------------------------------
// Client -> Server
// ---------------------------------------------------------------------------

export type ClientMessage =
  | CreateMatchMessage
  | JoinMatchMessage
  | RejoinMatchMessage
  | SetSpecialtyMessage
  | StartMatchMessage
  | CommandMessage
  | ResyncMessage
  | LeaveMatchMessage;

/** Create a new lobby; the sender becomes host. Response: `joined` then `lobby`. */
export interface CreateMatchMessage {
  readonly t: "create_match";
  readonly playerName: string;
  /** Defaults to `survivor`. */
  readonly specialty?: SpecialtyType;
}

/** Join an existing lobby by code. Response: `joined` then `lobby` to everyone. */
export interface JoinMatchMessage {
  readonly t: "join_match";
  readonly matchCode: string;
  readonly playerName: string;
  /** Defaults to `survivor`. */
  readonly specialty?: SpecialtyType;
}

/** Change specialty while still in the lobby. Response: `lobby` to everyone. */
export interface SetSpecialtyMessage {
  readonly t: "set_specialty";
  readonly specialty: SpecialtyType;
}

/** Reattach to a player slot after a disconnect. Response: `joined`, `lobby`, and `update` if started. */
export interface RejoinMatchMessage {
  readonly t: "rejoin_match";
  readonly matchCode: string;
  readonly rejoinToken: string;
}

/** Host only. Starts the match on a scenario (default `extraction`). Response: `map` then `update` to everyone. */
export interface StartMatchMessage {
  readonly t: "start_match";
  readonly scenario?: ScenarioType;
}

/** Command ids are client-chosen: 1 to 64 characters from this alphabet. */
export const COMMAND_ID_PATTERN = /^[A-Za-z0-9_-]{1,64}$/;

export function isValidCommandId(value: unknown): value is string {
  return typeof value === "string" && COMMAND_ID_PATTERN.test(value);
}

/**
 * A gameplay intent. Response: `update` (carrying this `commandId`) to everyone, or
 * `rejected` to the sender only. See docs/NETWORK-PROTOCOL.md, "Command reliability".
 */
export interface CommandMessage {
  readonly t: "command";
  /**
   * Unique per command, generated by the client (a UUID is fine). The server remembers
   * recent ids per player and answers a repeat with `DUPLICATE_COMMAND` without executing
   * it, so a retransmission after a lost acknowledgement is always safe.
   */
  readonly commandId: string;
  /**
   * The `update.revision` the client acted on. A mismatch is refused as `STALE_REVISION`
   * with the current revision, so a command composed against an old board never applies
   * to a newer one; the client then asks for a `resync`.
   */
  readonly baseRevision: number;
  readonly command: ClientCommand;
}

/** Ask for a fresh authoritative snapshot (`map` then `update`) on this socket. */
export interface ResyncMessage {
  readonly t: "resync";
}

/** Leave the lobby or match. Response: `lobby` (or `update`) to the others. */
export interface LeaveMatchMessage {
  readonly t: "leave_match";
}

// ---------------------------------------------------------------------------
// Server -> Client
// ---------------------------------------------------------------------------

export type ServerMessage =
  JoinedMessage | LobbyMessage | MapMessage | UpdateMessage | RejectedMessage | ErrorMessage;

export interface JoinedMessage {
  readonly t: "joined";
  readonly protocolVersion: number;
  readonly matchCode: string;
  readonly playerId: PlayerId;
  /** Secret for `rejoin_match`. Store it client-side; never show it to other players. */
  readonly rejoinToken: string;
}

export interface LobbyPlayer {
  readonly id: PlayerId;
  readonly name: string;
  readonly specialty: SpecialtyType;
  readonly present: boolean;
}

export interface LobbyMessage {
  readonly t: "lobby";
  readonly matchCode: string;
  readonly hostId: PlayerId;
  readonly maxPlayers: number;
  readonly started: boolean;
  readonly players: readonly LobbyPlayer[];
}

/**
 * The static board, sent once per socket before its first `update` (at match start and on
 * rejoin). It never changes during a match, so `update` omits it.
 */
export interface MapMessage {
  readonly t: "map";
  readonly map: GameMap;
}

/**
 * Everything in `GameState` except the map, which travels once in `MapMessage`, and
 * except zombies outside the team's current view, which the server leaves out so their
 * positions never reach a client (fog of war, docs/GAME-RULES.md).
 */
export type WireGameState = Omit<GameState, "map">;

/** Full authoritative snapshot (minus the map) plus the events that produced it. */
export interface UpdateMessage {
  readonly t: "update";
  /**
   * The authoritative state revision: 0 at match start, +1 for every accepted mutation
   * (a player command or a server presence change). A client discards an update whose
   * revision is below the last one it applied and sends `baseRevision` from it.
   */
  readonly revision: number;
  /** The accepted command that produced this update; absent for server-originated updates. */
  readonly commandId?: string;
  readonly state: WireGameState;
  readonly events: readonly GameEvent[];
}

/**
 * Why a command was not executed, as a closed machine-readable set. `detail` carries the
 * game-core `RejectionReason` for `INVALID_PHASE` and `INVALID_ACTION` so the client can
 * word it; nothing here is meant to be shown verbatim.
 */
export type CommandRejectionReason =
  | "MALFORMED_COMMAND"
  | "NOT_AUTHORIZED"
  | "MATCH_NOT_STARTED"
  | "DUPLICATE_COMMAND"
  | "STALE_REVISION"
  | "INVALID_PHASE"
  | "INVALID_ACTION";

/** The typed outcome of a command that was not executed. Sent to the sender only. */
export interface RejectedMessage {
  readonly t: "rejected";
  readonly commandId: string;
  readonly reason: CommandRejectionReason;
  readonly detail?: RejectionReason;
  /** The server's revision at the time; absent when no match is involved (malformed input). */
  readonly currentRevision?: number;
}

export type ErrorCode =
  | "MALFORMED_MESSAGE"
  | "INVALID_PLAYER_NAME"
  | "MATCH_NOT_FOUND"
  | "MATCH_FULL"
  | "MATCH_ALREADY_STARTED"
  | "MATCH_NOT_STARTED"
  | "NOT_IN_MATCH"
  | "ALREADY_IN_MATCH"
  | "NOT_HOST"
  | "INVALID_REJOIN_TOKEN"
  | "RATE_LIMITED"
  | "SESSION_REPLACED"
  | "INTERNAL_ERROR";

/** Session-level problems (never the outcome of a gameplay command). Sent to the sender only. */
export interface ErrorMessage {
  readonly t: "error";
  readonly code: ErrorCode;
  readonly message: string;
}
